config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # indexからdestroyまでの7つのルーティングを定義する。
  resources :books

  get 'top' => 'books#top'
  #ルートへアクセスした際のルーティング設定
  root to: 'books#top'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def top
  end

  def index
    @books = Book.all
  	@book = Book.new
  end

  def show
  	@book = Book.find(params[:id])
  end

  def create
  	book = Book.new(book_params)
	if book.save #ここでセーブされる。
	    flash[:notice] = "Book was successfully updated"
	    redirect_to book_path(book.id)
	else
    	@books = Book.all
  		@book = book
		render :index
	end
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def update
  	book = Book.find(params[:id])
	if book.update(book_params)
	    flash[:notice] = "Book was successfully updated"
	    redirect_to book_path(book)
	else
		@book = book
		render :edit
	end
  end

  def destroy
		book = Book.find(params[:id])
		book.destroy
		redirect_to books_path
  end

  private
  	def book_params
      params.require(:book).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<!-- 編集画面 -->

<h1>Editing Book</h1>
<!-- form_for部分 -->
<%= form_for(@book) do |f| %>

	<!-- バリデーションエラーメッセージの表示 -->
	<% if @book.errors.any? %>
	<h3>エラーが<%= @book.errors.count %>件あります。</h3>
	<ul>
		<% @book.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
	<% end %>
	<!-- ------------------------ -->

<div>
    <h4>title</h4>
    <%= f.text_field :title %>
    <h4>body</h4>
    <%= f.text_area :body %>
</div>
<div>
    <%= f.submit 'Update Book' %>
</div>
<% end %>

<%= link_to "Show", book_path(@book) %> | 
<%= link_to "Back", "/books" %>

app/views/books/index.html.erb
<!-- 一覧・投稿画面 -->

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
	<% @books.each do |book| %>
	<tr>
	  <td><%= book.title %></td>
	  <td><%= book.body %></td>
	  <td><%= link_to "Show", book_path(book.id) %></td>
	  <td><%= link_to "Edit", edit_book_path(book.id) %></td>
	  <td><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
	</tr>
	<% end %>
  </tbody>
</table>

<h2>New book</h2>
<%= form_for(@book) do |f| %>
	<!-- バリデーションエラーメッセージの表示 -->
	<% if @book.errors.any? %>
	<h3>エラーが<%= @book.errors.count %>件あります。</h3>
	<ul>
		<% @book.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
	<% end %>
	<!-- ------------------------ -->
	<div>
    	<h4>Title</h4>
    	<%= f.text_field :title %>
    	<h4>body</h4>
    	<%= f.text_area :body %>
	</div>

	<div>
    	<%= f.submit 'Create Book' %>
	</div>
<% end %>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<!-- サクセスメッセージの表示 -->
<p id="notice"><%= notice %></p>

<p><strong>title:</strong><%= @book.title %></p>
<p><strong>body:</strong><%= @book.body %></p>

<%= link_to "Edit", edit_book_path(@book) %> | 
<%= link_to "Back", "/books" %>

app/views/books/top.html.erb
<!-- トップページ -->
<h1>ようこそ Bookers へ！</h1>

<p><strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有することができます。</p>

<a href="/books">start</a>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>